[options]
addons_path = C:\jworks\odoo15\addons,C:\jworks\odoo15\addons_custom,C:\jworks\odoo15\themes15,C:\jworks\odoo15\common,C:\jworks\odoo15\reports15,C:\jworks\odoo15\reports15/accounting,C:\jworks\odoo15\reports15/purchase,C:\jworks\odoo15\reports15/inventory,C:\jworks\odoo15\reports15/BASE,C:\jworks\odoo15\reports15/JUPITER,C:\jworks\odoo15\reports15/SALES
admin_passwd = 123
;db_name = 
db_host = localhost
db_password = odoo15_new
db_port = 5434
db_user = odoo15_new
;dbfilter = ^%d$
http_port = 8075
;limit_time_real = 10000
;data_dir=C:\jworks\justoworks_2025-07-04
